In [1]:
!unzip dataset.zip

Archive:  dataset.zip
   creating: dataset/
   creating: dataset/light_1/
  inflating: dataset/light_1/47.jpeg  
  inflating: dataset/light_1/13.jpeg  
  inflating: dataset/light_1/109.jpeg  
  inflating: dataset/light_1/68 (copy).jpeg  
  inflating: dataset/light_1/12.jpeg  
  inflating: dataset/light_1/47 (3rd copy).jpeg  
  inflating: dataset/light_1/47 (another copy).jpeg  
  inflating: dataset/light_1/47 (copy).jpeg  
  inflating: dataset/light_1/50.jpeg  
  inflating: dataset/light_1/56 (copy).jpeg  
  inflating: dataset/light_1/60.jpeg  
  inflating: dataset/light_1/66.jpeg  
  inflating: dataset/light_1/66 (copy).jpeg  
  inflating: dataset/light_1/11.jpeg  
  inflating: dataset/light_1/93 (copy).jpeg  
  inflating: dataset/light_1/100.jpeg  
  inflating: dataset/light_1/104 (3rd copy).jpeg  
  inflating: dataset/light_1/104 (another copy).jpeg  
  inflating: dataset/light_1/104 (copy).jpeg  
  inflating: dataset/light_1/109 (3rd copy).jpeg  
  inflating: dataset/light_1/109 (a

In [1]:
import pickle
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
from tensorflow.keras import regularizers
from tensorflow.keras.metrics import Recall,Precision
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Dropout,Activation,Conv2D,MaxPooling2D,Dropout


model = Sequential()

model.add(Conv2D(64, (3,3), activation='relu', input_shape=(299,299,3)))
model.add(MaxPooling2D(2, 2))

model.add(Conv2D(128, (3,3), activation='relu'))
model.add(MaxPooling2D(2, 2))

model.add(Conv2D(128, (3,3), activation='relu'))
model.add(MaxPooling2D(2, 2))

model.add(Flatten())

model.add(Dense(128,kernel_regularizer=regularizers.l2(0.01),activity_regularizer=regularizers.l1(0.01)))
model.add(Activation('relu'))

model.add(Dropout(0.2))

model.add(Dense(32))
model.add(Activation('relu'))

model.add(Dropout(0.2))

model.add(Dense(3))
model.add(Activation('softmax'))


model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='sparse_categorical_crossentropy',
              metrics = ['accuracy'])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [3]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1/255, validation_split=0.1,
                     rotation_range=90,
                     width_shift_range=0.2,
                     height_shift_range=0.2,
                     horizontal_flip=True,
                     vertical_flip=True,
                     fill_mode="wrap",
                     zoom_range=0.2)

train_generator = train_datagen.flow_from_directory(
        "./dataset", 
        target_size=(299, 299),
        color_mode='rgb',
        batch_size=1,
        seed=3,
        class_mode='categorical')

Found 508 images belonging to 3 classes.


In [4]:
data_list = []
batch_index = 0

while batch_index <= train_generator.batch_index:
    data = train_generator.next()
    data_list.append(data[0])
    batch_index = batch_index + 1

# now, data_array is the numeric data of whole images
x = np.asarray(data_list)

print(np.shape(x))
#print(x)

(508, 1, 299, 299, 3)


In [0]:
y = np.asarray(train_generator.labels)

In [6]:
print(np.shape(y))
print(y)

(508,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2

In [7]:
data = np.zeros((508,2,299,299,3))
data[:,0,:,:,:] = x[:,0,:,:,:]
data[:,1,0,0,0] = y
import random
random.shuffle(data)
print(np.shape(data))
x = data[:,0,:,:,:]
y = data[:,1,0,0,0]
print(np.shape(x))
print(np.shape(y))

(508, 2, 299, 299, 3)
(508, 299, 299, 3)
(508,)


In [8]:
print(x)
print(y)

[[[[0.1873164  0.26574779 0.3010419 ]
   [0.13725491 0.21568629 0.25098041]
   [0.13725491 0.21568629 0.25098041]
   ...
   [0.01176471 0.08627451 0.1137255 ]
   [0.02151423 0.09602404 0.12347502]
   [0.02745098 0.10196079 0.12941177]]

  [[0.21722387 0.29565525 0.33094937]
   [0.13725491 0.21568629 0.25098041]
   [0.14599498 0.22442636 0.2597205 ]
   ...
   [0.01176471 0.08627451 0.1137255 ]
   [0.01828988 0.09279969 0.12025067]
   [0.02854759 0.1030574  0.13050839]]

  [[0.28688571 0.36531711 0.40061122]
   [0.19001545 0.26844683 0.30374098]
   [0.20626883 0.28470021 0.31999433]
   ...
   [0.01440393 0.08891374 0.11636472]
   [0.01822043 0.09273024 0.12018123]
   [0.03137255 0.10588236 0.13333334]]

  ...

  [[0.01176471 0.09411766 0.1137255 ]
   [0.01176471 0.09411766 0.1137255 ]
   [0.01176471 0.09411766 0.1137255 ]
   ...
   [0.11932414 0.12890565 0.17901686]
   [0.20784315 0.22352943 0.27058825]
   [0.20784315 0.22352943 0.27058825]]

  [[0.01176471 0.09411766 0.1137255 ]
   [0.0

In [9]:
import keras
from tensorflow.keras.callbacks import EarlyStopping,CSVLogger,ModelCheckpoint,TensorBoard
filename="metrics.csv"
es=EarlyStopping(monitor='loss', min_delta=0, patience=3, mode='min', baseline=None, restore_best_weights=True)
csv=CSVLogger(filename, separator=',', append=False)
checkpoint=ModelCheckpoint("weights.{epoch}-{val_acc:.2f}.hdf5", monitor='val_acc', verbose=0, save_best_only=False, save_weights_only=False, mode='auto', period=1)
tensorboard=TensorBoard(log_dir='./logs', histogram_freq=0, batch_size=32, write_graph=True, write_grads=False, write_images=False, embeddings_freq=0, embeddings_layer_names=None, embeddings_metadata=None, embeddings_data=None, update_freq='epoch')

Using TensorFlow backend.


In [10]:
model.fit(x, y, epochs=25, batch_size=64, callbacks=[es, tensorboard])
#history = model.fit_generator(train_generator,epochs=25,verbose=2,callbacks=[es, tensorboard])

Train on 508 samples
Epoch 1/25
508/508 [==============================] - 17s 34ms/sample - loss: 2.9271 - acc: 0.7717
Epoch 2/25
508/508 [==============================] - 7s 14ms/sample - loss: 1.8559 - acc: 0.8701
Epoch 3/25
508/508 [==============================] - 7s 14ms/sample - loss: 1.3146 - acc: 0.8720
Epoch 4/25
508/508 [==============================] - 7s 14ms/sample - loss: 0.9892 - acc: 0.8720
Epoch 5/25
508/508 [==============================] - 7s 14ms/sample - loss: 0.8018 - acc: 0.8720
Epoch 6/25
508/508 [==============================] - 7s 14ms/sample - loss: 0.6936 - acc: 0.8720
Epoch 7/25
508/508 [==============================] - 7s 14ms/sample - loss: 0.6383 - acc: 0.8780
Epoch 8/25
508/508 [==============================] - 7s 14ms/sample - loss: 0.5985 - acc: 0.8799
Epoch 9/25
508/508 [==============================] - 7s 14ms/sample - loss: 0.5739 - acc: 0.8799
Epoch 10/25
508/508 [==============================] - 7s 14ms/sample - loss: 0.5546 - acc: 0.88

In [11]:
model.evaluate(x, y, verbose=1)

508/508 [==============================] - 5s 10ms/sample - loss: 0.2100 - acc: 0.9941


[0.21002765480927596, 0.9940945]

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 297, 297, 64)      1792      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 148, 148, 64)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 146, 146, 128)     73856     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 73, 73, 128)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 71, 71, 128)       147584    
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 35, 35, 128)       0         
_________________________________________________________________
flatten (Flatten)            (None, 156800)            0

In [0]:
model.save('model_1.h5')

In [14]:
!pwd

/content


In [0]:
import zipfile
import os
def zipfolder(foldername, target_dir):            
    zipobj = zipfile.ZipFile(foldername + '.zip', 'w', zipfile.ZIP_DEFLATED)
    rootlen = len(target_dir) + 1
    for base, dirs, files in os.walk(target_dir):
        for file in files:
            fn = os.path.join(base, file)
            zipobj.write(fn, fn[rootlen:])

In [0]:
zipfolder('logs',"./logs")

In [0]:
!rm -rf logs